apiVersion: v1
kind: Service
metadata:
  name: httpecho-svc
  labels:
    k8s-app: httpecho
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    name: http
    nodePort: 30000
  selector:
    k8s-app: httpecho
